# Generated by Django 3.0.7 on 2020-11-18 18:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=15)),
                ('lastname', models.CharField(max_length=15)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=10)),
                ('phoneno', models.IntegerField()),
                ('emailid', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=50)),
                ('children', models.IntegerField()),
                ('adults', models.IntegerField()),
                ('roomtype', models.CharField(max_length=10)),
                ('aadharno', models.CharField(max_length=15)),
                ('daysstayed', models.IntegerField()),
                ('date_visited', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
