# Generated by Django 3.0.7 on 2020-11-18 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomno', models.IntegerField()),
                ('roomtype', models.CharField(max_length=10)),
                ('vacancy', models.BooleanField(default=False)),
                ('price', models.BooleanField(default=0)),
            ],
        ),
    ]
