# Generated by Django 3.0.7 on 2020-11-19 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20201119_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='occupied_by',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.Customer'),
        ),
    ]
