# Generated by Django 3.0.7 on 2020-11-19 09:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_customer_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_visited',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 19, 9, 21, 3, 549576, tzinfo=utc)),
        ),
    ]
