# Generated by Django 3.0.7 on 2020-11-19 17:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_auto_20201119_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_visited',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 19, 17, 8, 29, 943036, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=15)),
                ('price', models.IntegerField()),
                ('used_by', models.ManyToManyField(default=0, null=True, to='employee.Customer')),
            ],
        ),
    ]
