# Generated by Django 3.0.7 on 2020-11-19 18:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_auto_20201119_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_visited',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 19, 18, 1, 2, 387508, tzinfo=utc)),
        ),
    ]
