# Generated by Django 3.0.7 on 2020-11-19 18:51

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_auto_20201120_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_visited',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 19, 18, 51, 31, 404474, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customerlog',
            name='date_visited',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 19, 18, 51, 31, 642396, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='uses',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employee.Customer'),
        ),
        migrations.AlterField(
            model_name='uses',
            name='time_used',
            field=models.TimeField(default=datetime.datetime(2020, 11, 19, 18, 51, 31, 646390, tzinfo=utc)),
        ),
    ]
