# Generated by Django 3.0.7 on 2020-11-19 18:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_auto_20201120_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='used_by',
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_visited',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 19, 18, 55, 20, 324308, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customerlog',
            name='date_visited',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 19, 18, 55, 20, 592721, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='uses',
            name='time_used',
            field=models.TimeField(default=datetime.datetime(2020, 11, 19, 18, 55, 20, 596767, tzinfo=utc)),
        ),
    ]
