# Generated by Django 3.0.7 on 2020-11-19 19:06

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_auto_20201120_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_visited',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 19, 19, 5, 59, 468292, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customerlog',
            name='date_visited',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 19, 19, 5, 59, 747186, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='uses',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Customer'),
        ),
        migrations.AlterField(
            model_name='uses',
            name='service_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Services'),
        ),
        migrations.AlterField(
            model_name='uses',
            name='time_used',
            field=models.TimeField(default=datetime.datetime(2020, 11, 19, 19, 5, 59, 748189, tzinfo=utc)),
        ),
    ]
