# Generated by Django 3.0.7 on 2020-11-26 16:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0017_auto_20201122_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_visited',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 26, 16, 38, 53, 977832, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customerlog',
            name='date_visited',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 26, 16, 38, 54, 161341, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='uses',
            name='time_used',
            field=models.TimeField(default=datetime.datetime(2020, 11, 26, 16, 38, 54, 164331, tzinfo=utc)),
        ),
    ]
