# Generated by Django 3.0.7 on 2020-11-26 16:55

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0018_auto_20201126_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerlog',
            name='aadharno',
            field=models.CharField(max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerlog',
            name='address',
            field=models.CharField(max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerlog',
            name='adults',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerlog',
            name='age',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerlog',
            name='children',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerlog',
            name='daysstayed',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerlog',
            name='emailid',
            field=models.CharField(max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerlog',
            name='phoneno',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerlog',
            name='room_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.Room'),
        ),
        migrations.AddField(
            model_name='customerlog',
            name='roomtype',
            field=models.CharField(max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerlog',
            name='sex',
            field=models.CharField(max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_visited',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 26, 16, 53, 37, 451556, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customerlog',
            name='date_visited',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 26, 16, 53, 37, 681771, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='uses',
            name='time_used',
            field=models.TimeField(default=datetime.datetime(2020, 11, 26, 16, 53, 37, 681771, tzinfo=utc)),
        ),
    ]
