# Generated by Django 2.2.10 on 2020-12-09 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0023_auto_20201128_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerlog',
            name='room_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.Room'),
        ),
    ]
