# Generated by Django 2.2.10 on 2020-12-09 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0024_auto_20201209_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='occupied_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.Customer'),
        ),
    ]
