# Generated by Django 2.2.10 on 2021-01-07 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0026_auto_20210107_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='customer',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.Customer'),
        ),
    ]
