# Generated by Django 2.2.10 on 2021-01-10 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0002_auto_20201210_0009'),
        ('employee', '0027_auto_20210107_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='emp_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='head.Employee'),
        ),
    ]
