# Generated by Django 3.1.3 on 2020-11-12 19:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=30)),
                ('email_id', models.CharField(max_length=30)),
                ('phone_no', models.IntegerField()),
                ('age', models.IntegerField()),
                ('aadhar_number', models.CharField(max_length=15)),
                ('sex', models.CharField(max_length=5)),
                ('address', models.CharField(max_length=100)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
