# Generated by Django 2.2.10 on 2020-12-09 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='datejoined',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
