# Generated by Django 2.2.10 on 2021-01-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0002_auto_20201210_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='aadharno',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emailid',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phoneno',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sex',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
